version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:3000"
    env_file:
      - .env.production
    depends_on:
      - db
    
    # --- ADICIONE ESTA LINHA ---
    restart: always

  db:
    image: postgres:15
    restart: always # Esta linha você já tinha
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: password
      POSTGRES_DB: readowl
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
